### ISSUE TITLE
Second Webcam URL will be ignored

### ISSUE THREAD

**Issue by tis-cs** [mikedmor/OctoPrint_MultiCam#13]
Hi,

I'm using a Axis ip camera to see what is happening while printing.
Now I tried to use the pi cam via mjpeg-streamer, which is for my timelapse, to set it as a second cam.

![image](https://user-images.githubusercontent.com/24519878/54115968-095edc80-43ee-11e9-95a4-eab93b2c182a.png)

But all I get is a error which shows that the plugin tries to stream the Axis cam:

![image](https://user-images.githubusercontent.com/24519878/54116038-30b5a980-43ee-11e9-9cfe-29674597831c.png)

What am I doing wrong or is it a bug?

Thanks in advance!

BR

**Comment by harryurban** [comment]
Hast du das Problem schon gelöst?
Siehst du was im Netzwerk tab von den dev Tools? Ein 401 oder ähnliches oder CORS Probleme?

**Comment by tis-cs** [comment]
ehrlich gesagt habe ich einfach die Pi-Cam durch eine Logitech USB Cam getauscht. Damit läuft es, allerdings nicht mit der 127.0.0.1 sondern ich muss die IP des Raspi explizit angeben.

**Comment by harryurban** [comment]
hast du mal probiert host / ip wegzulassen?

also `/webcam/?action=stream` als url einzugeben?

**Comment by tis-cs** [comment]
habe ich eben gemacht. Geht soweit mit der USB Cam. Raspi-Cam hängt aktuell ja nicht mehr dran.
Ist aber auch nicht mehr wirklich interessant, da die Qualität der Cam nicht gerade gut ist.

**Comment by harryurban** [comment]
hab hier bisschen meine anleitung für usb webcam + picam aufgeschrieben falls du doch noch beide anschliessen willst:
https://github.com/mikedmor/OctoPrint_MultiCam/issues/12

**Comment by harryurban** [comment]
http://www.thedoble.com/3d-printing/running-two-webcams-with-octoprint-for-hd-timelapses/

**Comment by BramBertels** [comment]
I had the same issue. Removing the ip address and just using /webcam/?action=stream and /webcam2/?action=stream worked for me

**Comment by mikedmor** [comment]
@BramBertels is correct, If using a local webcam plugged into the pi, then do not include the address, instead just use /webcam2/?action=stream

@harryurban also has a great write up on how to get everything configured.
