### ISSUE TITLE
Add mirror option

### ISSUE THREAD

**Issue by xlkiller** [mikedmor/OctoPrint_MultiCam#18]
Hi

I have multi cam installed but one is horizontal and vertical miror... And others No 

Please add this function.

Thank's

**Comment by StefanCohen** [comment]
Hi. I agree. One of my cams is mounted upside down on the gantry of the printer. I think it would be great if each stream could have individual options to rotate by 90deg, flipH and FlipV just like the default octoprint cam.

**Comment by mikedmor** [comment]
Version 0.2.7, introduced Rotate, Flip and Ratio.
