### ISSUE TITLE
Camera rotation

### ISSUE THREAD

**Issue by Darkmadda** [mikedmor/OctoPrint_MultiCam#2]
We need an option for rotating the view like how the primary camera can be rotated in the main settings

**Comment by mikedmor** [comment]
I will look into adding a rotation setting in one of the next few updates. I'm currently running from an external pi that handles all of that for me before the feed is streamed. But i can see the need for it if you are using a camera directly on the pi.

**Comment by jeremyrclark** [comment]
I'd like to second this request. I use OctoPi with a secondary RaspiCam that is mounted upside down. I use OctoPod to view my feeds remotely and it isn't able to rotate or flip the camera via settings as it relies on whatever MultiCam provides.

**Comment by mikedmor** [comment]
Version 0.2.8 should now include options for rotating and flipping the camera.

**Comment by jeremyrclark** [comment]
Thank you!
