### ISSUE TITLE
[Bug] Loose configuration from last update

### ISSUE THREAD

**Issue by courtpl** [mikedmor/OctoPrint_MultiCam#24]
It seems a problem between the Dashboard and Multicam pluggin
The button name are inverted and the camera configuration reset as defaut camera, and the second camera is displayed on the Dashbord instead of the defaut camera.

The problem appear after each reboot

**Comment by StefanCohen** [comment]
Hi. I'm the author of the Dashboard. That's my fault. A Dashboard PR accidentally inverted the multi_cam settings. I'm working on a fix for that so this issue may be closed.
