### ISSUE TITLE
Finding ip address for multiple cams

### ISSUE THREAD

**Issue by Ajakobsen** [mikedmor/OctoPrint_MultiCam#25]
Hi, 
So I have a Logitech and a raspberry pi camera connected. I installed the multicam plugin and having troubles configuring it. 

For my logitech the URL is set to: /webcam/?action=stream which is clear and showing in the control tab. But what should i type for the URL for my RP camera?

![image](https://user-images.githubusercontent.com/5802085/84155792-0deac880-aa69-11ea-81ec-c73593457d76.png)

**Comment by mikedmor** [comment]
If you are using two webcams directly on the same rpi, then you will need to do some addition configuration,

This page has a great tutorial on how to get multiple webcams configured on your rpi:
http://www.thedoble.com/3d-printing/running-two-webcams-with-octoprint-for-hd-timelapses/
