### ISSUE TITLE
config.yaml second camera data overwritten with first camera data

### ISSUE THREAD

**Issue by wseifert** [mikedmor/OctoPrint_MultiCam#31]
in config.yaml sometimes the data for the second cam are overwritten with data from first cam, so both Webcam buttons point to the same first cam. Removing the write attrib (chmod -x config.yaml) does not help :(

**Comment by YoungCereal** [comment]
Same at me all cams are overwritten

**Comment by ProfEngr** [comment]
Mine gets stuck frequently on the webcam2 URL in the Octoprint webcam settings. It's easy to correct, but the randomness is odd. It's done it mid-session and after a reboot.

**Comment by n3roGit** [comment]
Here the same

**Comment by n3roGit** [comment]
As a workaround create the first cam with the addon "double". Then you have one of the buttons double, but nothing will be overwritten.

![image](https://user-images.githubusercontent.com/8565847/101604674-8c68f880-3a01-11eb-8310-8370b16c4c12.png)
