### ISSUE TITLE
2 Usb cams with Multicam

### ISSUE THREAD

**Issue by nickeeey** [mikedmor/OctoPrint_MultiCam#34]
Hi, i got 2 USB Cams (c270). How can i setup my Octoprint to use both? I cant find any up to date guide for it.
Thanks

**Comment by ozett** [comment]
good question. i am also interested in the answer...

**Comment by MetahumanFamily** [comment]
https://community.octoprint.org/t/setting-up-multiple-webcams-in-octopi-the-right-way/32669

I followed these steps and now I have a C270, C920 and PiCam all running perfectly.
