### ISSUE TITLE
Cannot get feed to work with any full URL?

### ISSUE THREAD

**Issue by gleep52** [mikedmor/OctoPrint_MultiCam#45]
I have a blue iris server and have some Wyze V2 cameras running through it - and blue iris has a native re-encoder for http streams.  If I browse to http://server_IP_Address:port/mjpg/CamName in any browser, it immediately starts streaming the motion jpeg stream.  If I put in /image/CamName I get a still image.  There is no password required on my local network - yet somehow Multicam refuses to display the video or still image.  Any way to getting this to work?

**Comment by OllisGit** [comment]
What is the difference to your other ticket #46 ?

**Comment by gleep52** [comment]
Just a different system that did the same thing - sorry for the duplicate post.
