### ISSUE TITLE
dom ID conflict with main Octoprint UI

### ISSUE THREAD

**Issue by LazeMSS** [mikedmor/OctoPrint_MultiCam#47]
Your plugin is using the unique ids for the main webcams layers in OctoPrint UI and thereby causing ID conflicts etc.

https://github.com/mikedmor/OctoPrint_MultiCam/blob/355b11398bffcf4987f2f9638498390a0cd404d3/octoprint_multicam/templates/multicam_settings.jinja2#L62

Both: webcam_container and webcam_rotator

**Comment by OllisGit** [comment]
Hi,

PR #48 fix the issue.

Btw @LazeMSS was there a reported issue?

**Comment by LazeMSS** [comment]
No I found the bug when trying to add new features in UI Customizer ;)

**Comment by LazeMSS** [comment]
Thanks
