### ISSUE TITLE
Since last update, cameras no longer change

### ISSUE THREAD

**Issue by JesNoFear** [mikedmor/OctoPrint_MultiCam#58]
Since the last update (I updated yesterday and today) both the toggle buttons on the control tab and the drop down menu no longer switch to the camera selected. It stays on the default camera.

Looks like my OctoPrint updated as well.

I have 3 setups, 2 on RPI 4's and one that's a bit beefier. below are the support files.

[octoprint-systeminfo-CR-10SProV2.zip](https://github.com/mikedmor/OctoPrint_MultiCam/files/11659943/octoprint-systeminfo-CR-10SProV2.zip)
[octoprint-systeminfo-Voron2.4.zip](https://github.com/mikedmor/OctoPrint_MultiCam/files/11659944/octoprint-systeminfo-Voron2.4.zip)

**Comment by mikedmor** [comment]
Octoprint 1.9.0 does not support MultiCam 0.3.1, instead 0.3.1 just adds a RC channel that can be switch to via the Software Update tab, Upon switching to 0.4.0rc4 Multicam should work again.

**Comment by JesNoFear** [comment]
Thank you
