### ISSUE TITLE
multiple USB logitech cameras plugged into Pi

### ISSUE THREAD

**Issue by redstopgreengo123** [mikedmor/OctoPrint_MultiCam#7]
can not utilize plugin with multiple logitech cams plugged into pi. can not locate address for other cameras plugged into device to enter in the address field.

**Comment by harryurban** [comment]
Start second m-jpg instance for 2nd device.

**Comment by harryurban** [comment]
https://github.com/mikedmor/OctoPrint_MultiCam/issues/12  (there I wrote how to do that)

**Comment by harryurban** [comment]
http://www.thedoble.com/3d-printing/running-two-webcams-with-octoprint-for-hd-timelapses/

**Comment by mikedmor** [comment]
Thank you for the write up @harryurban.
