### ISSUE TITLE
Can't change Name or URL after first edit

### ISSUE THREAD

**Issue by Viginox** [mikedmor/OctoPrint_MultiCam#8]
When setting up multiple cameras, you have only one change to get it right.
After saving the entry the first time you can not change it anymore. To change something you have to reboot the system and then you also can edit it **once** until it resets when you hit the Save button.

**Comment by SHPL00P** [comment]
Was there ever a work around or solution to this issue? no matter what i do i end up with only one cam viewable in the webcam 1 button, the second always says:

Webcam stream not loaded

"It might not be configured correctly or require authentication. You can change the URL of the stream under "Settings" > "Webcam & Timelapse" > "Webcam" > "Stream URL". If you don't have a webcam you can also just disable webcam support there.

Currently configured stream URL: /webcam/?action=stream"


that last part being the part that saves over itself in the webcam 1 url but doesnt actually effect webcam 1s feed but does change the YAML directory entry. im lost

**Comment by timur-tabi** [comment]
The work-around is to edit ~/.octoprint/config.yaml directly.
